spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://139.155.33.105:2432/yldsj
    url: jdbc:postgresql://10.250.0.120/yldsj
    username: postgres
#    password: 123456
    password: 1234


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto : update
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200  #连接池最大连接数(只用负数值表示没有限制)
        max-wait: -1   #连接池最大阻塞等待时间(只用负数值表示没有限制)
        max-idle: 10   #连接池中的最大空闲连接
        min-idle: 0    #连接池中的最小空闲连接
      #连接超时时间(毫秒)
    timeout: 1000
mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath*:com/ydl/mapper/*.xml
debug: true
server:
  port: 8887
  undertow:
    accesslog:
      enabled: true
      dir: logs
pagehelper:
  helper-dialect: postgresql
  reasonable: true
  support-methods-arguments: true
  params:
logging:
  file: log/log.log
  level:
    com.fishpro.log: debug
